### ISSUE TITLE
C'ant get the exemple to work

### ISSUE THREAD

**Issue by yassinevic** [waitingsong/node-myca#2]
Hello.

I was trying to run the pfx example but the error below stoped me.
file of param configFile  of signOpts not exists: ~\.myca/.config"

i cant figure out how to create the need conf file.

[My code]
	myca.initDefaultCenter().catch(console.error)
/*
	myca
	   .initCaCert({
		 days: 10950,  // 30years
		 pass: 'mycapass',
		 CN: 'My Root CA',    // Common Name
		 O: 'My Company',   // Organization Name (eg, company)
		 C: 'CN',   // Country Name (2 letter code)
	   }).catch(console.error)
   */
	

		myca
		.genCert({
			centerName: 'default',
			caKeyPass: 'mycapass',
			kind: 'client',   // pfx cert
			days: 730,
			pass: 'fooo',   // at least 4 letters
			CN: 'www.waitingsong.com',    // Common Name
			C: 'CN',   // Country Name (2 letter code)
		})
		.then((ret) => {
		console.log(ret.pfxFile)
		})
		.catch(console.error)

**Comment by waitingsong** [comment]
If works not yes, pls try myca-cli  https://www.npmjs.com/package/myca-cli

**Comment by ryaninvents** [comment]
Documentation specifies that the exposed methods return a Promise, but they return an `rxjs` Observable. I have started to make progress by adding `.toPromise()` after the method call. Not sure if it works in all cases, but it's a start.

**Comment by waitingsong** [comment]
docs fixed
thanks
